### ISSUE TITLE
--- FAIL: TestBroker_RemovePeer: race detected during execution of test

### ISSUE THREAD

**Issue by davecheney** [travisjeffery/jocko#27] opened 2017-02-12 23:41 UTC
http://paste.ubuntu.com/23985334/

**Comment by travisjeffery** [comment] 2017-02-13 03:56
Seems to be fixed after merging a change that split the serf and raft pkgs from the broker's pkg—because they don't access the same peers map anymore. I was able to reproduce it before but can't now. Thanks for making the issue.

- 8145ad3b35bedca7863b418e9662aa6db98ec5eb
- 65595df9f002b906692c48568eb837b249eb4a18

**Comment by davecheney** [comment] 2017-02-13 04:02
I don't believe this issue is fixed, I am using a revision newer than both
you quoted.

**Comment by travisjeffery** [comment] 2017-02-13 04:50
So you pulled and reproduced it after I left that comment? Just checking in case you're looking at the dates of when the commits were made rather than when they were merged into master.

**Comment by davecheney** [comment] 2017-02-13 04:53
I'm currently at fee05bf. Would you accept a PR to add -race detection to
your CI?

**Comment by travisjeffery** [comment] 2017-02-13 04:59
Yeah that commit's behind. See where it in relation to the other commits here: https://github.com/travisjeffery/jocko/commits/master

Absolutely. I was gonna add it, but it'd cool if you wanted to do it.

**Closed** 2017-02-14 14:48 UTC
